const menuData = [
    {
        id: 1,
        image: "https://i.imgur.com/JftOGbD.png",
        title: "Pattymelt",
        description: "Pan de molde, doble carne, doble cheddar, cebolla crispy, salsa de la casa.",
        rating: "8.1",
        price: "12000",
    },
    {
        id: 2,
        image: "https://i.imgur.com/nP4kfsT.png",
        title: "Rodeo",
        description: "Doble carne, doble cheddar, bacon, dedos de muzzarella, salsa de la casa.",
        rating: "9.2",
        price: "13500",
    },
    {
        id: 3,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Bacon-King.png",
        title: "Sinaloa",
        description: "Doble carne, pepinillos, guacamole, cebolla, lechuga, tomate, mayonesa.",
        rating: "8.5",
        price: "12500",
    },
    {
        id: 4,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Foto-web-carne_400x400-1.png",
        title: "BBQ Lover",
        description: "Doble carne, queso gouda, cebolla caramelizada, salsa BBQ.",
        rating: "9.0",
        price: "14000",
    },
    {
        id: 5,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Chili-King-carne-1.png",
        title: "Cheddar Bacon",
        description: "Doble carne, triple cheddar, bacon crujiente, salsa especial.",
        rating: "8.7",
        price: "13000",
    },
    {
        id: 6,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Whopper-con-Queso.png",
        title: "Hawaiana",
        description: "Carne, queso suizo, piña grillada, jamón, salsa teriyaki.",
        rating: "8.9",
        price: "14500",
    },
    {
        id: 7,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Stacker-Triple-3.png",
        title: "Spicy Burger",
        description: "Carne, jalapeños, queso pepper jack, salsa picante de la casa.",
        rating: "8.4",
        price: "12800",
    },
    {
        id: 8,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Stacker-Cuadruple-2.png",
        title: "Portobello",
        description: "Carne, queso brie, champiñones portobello, rúcula, salsa de ajo.",
        rating: "8.8",
        price: "13700",
    },
    {
        id: 9,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Papas-Cheddar-1.png",
        title: "Papas Cheddar",
        description: "Papas fritas con queso cheddar.",
        rating: "8.0",
        price: "11500",
    },
    {
        id: 10,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Napolitano-XL.png",
        title: "Mexicana",
        description: "Carne, queso cheddar, guacamole, pico de gallo, nachos crujientes.",
        rating: "9.1",
        price: "14200",
    },
    {
        id: 11,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/napolitano-MEGA-2.png",
        title: "Veggie Delight",
        description: "Hamburguesa de garbanzos, lechuga, tomate, aguacate, hummus.",
        rating: "8.3",
        price: "12000",
    },
    {
        id: 12,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Cheese-Onion-1.png",
        title: "Cheesy Overload",
        description: "Triple carne, queso cheddar, queso suizo, queso mozzarella.",
        rating: "9.4",
        price: "16500",
    },
    {
        id: 13,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Long-clasico-1.png",
        title: "Truffle Burger",
        description: "Carne, queso gouda, aceite de trufa, champiñones, rúcula.",
        rating: "9.3",
        price: "15000",
    },
    {
        id: 14,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/King-de-Pollo-Morron.png",
        title: "Crispy Chicken",
        description: "Pollo crujiente, queso cheddar, lechuga, tomate, mayonesa.",
        rating: "8.6",
        price: "12800",
    },
    {
        id: 15,
        image: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-bk-argentina/home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/King-de-Pollo-Frances-con-huevo-1.png",
        title: "Black Angus",
        description: "Carne black angus, queso azul, cebolla caramelizada, salsa especial.",
        rating: "9.5",
        price: "17000",
    },
];

export default menuData;
